services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./sql/001_init.sql:/docker-entrypoint-initdb.d/init.sql

  wordpress:
    image: wordpress:6-php8.2-apache
    ports:
      - 80:80
    volumes:
      - /home/alex/git/wp-theme-hcg/shooters:/var/www/html/wp-content/themes/shooters
      - .:/var/www/html/wp-content/plugins/handball
      - /home/alex/git/hc-goldau.ch:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DEBUG: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links: 
      - mariadb:db
    environment:      
      MYSQL_ROOT_PASSWORD: 1234
      UPLOAD_LIMIT: 100000000
