services:
  mariadb:    
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./wp-plugin-handball/handball/sql/001_init.sql:/docker-entrypoint-initdb.d/init.sql

  wordpress:
    image: wordpress:6-php8.2-apache
    ports:
      - 80:80
    volumes:
      - ./wp-theme-shooters/shooters:/var/www/html/wp-content/themes/shooters
      - ./wp-plugin-handball/handball:/var/www/html/wp-content/plugins/handball
      - ./data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DEBUG: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links: 
      - mariadb:db
    environment:      
      MYSQL_ROOT_PASSWORD: 1234
      UPLOAD_LIMIT: 100000000
